### ISSUE TITLE
Give innerJoinOn a fixity 

### ISSUE THREAD

**Issue by bergmark** [silkapp/girella#4]
But what should it be?

**Comment by hesselink** [comment]
Looking at our code base, lower than 9 (for `(.)`). Other than that, perhaps look at the arrow operators? `(***)` and `(&&&)` have fixity 3. Would you want joins to bind stronger or less strong than these? Then `(+++)` and `(|||)` have 2, but are less common (is `QueryArr` even an `ArrowChoice`)? The final batch, `(>>>)` and `(^>>)` plus the other directions for them, has 1.

**Comment by bergmark** [comment]
4 is somewhat arbitrary... but works well for our purposes
