### ISSUE TITLE
`like` operator support for more text types

### ISSUE THREAD

**Issue by c-lewis** [silkapp/girella#8]
I would like to be able to use the `like` operator on more than the `PGText` type it currently supports (e.g. `PGCitext`). The obvious way to do this seems to be to add a `PGString` class (or some appropriate name) with instances for all of the text-like types, similar to the `PGOrd` class, and switch the constraint on `like` to require this class. Full disclosure, I haven't yet attempted to make this change and play with it; I'm sure this is not the only way to handle this problem (or the only time this will come up), so I would appreciate some opinions.

**Comment by hesselink** [comment]
Hi @c-lewis, this isn't the [official opaleye repository](https://github.com/tomjaguarpaw/haskell-opaleye/issues), but our layer on top. So you might be better off filing this in the official repo, which also contains `PGOrd`.

**Comment by c-lewis** [comment]
Thanks! I was aware this isn't the official repository, but for some reason I got it stuck in my head that your library was providing the `PGOrd` facility. I'll post this issue to the Opaleye repository.

I'm a big fan of the layer you guys have built. Thank you.
